ckfinder:
  connector:
    authenticationClass: App\CustomCKFinderAuth\CustomCKFinderAuth
    resourceTypes:
      MyResource:
        name: MyResource
        backend: default
        directory: myResource