knpu_oauth2_client:
    clients:
        # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
        keycloak:
            # must be "keycloak" - it activates that type!
            type: keycloak
            # add and set these environment variables in your .env files
            client_id: website
            client_secret: "%env(KEYCLOAK_COMMON_SECRET)%"
            # a route name you'll create
            redirect_route: login_check
            redirect_params: {}
            # Keycloak server URL
            auth_server_url: "https://login.%env(DEVDOMAIN)%/auth"
            # Keycloak realm
            realm: "%env(DEVDOMAIN)%"

            # Optional: Encryption algorith, i.e. RS256
            # encryption_algorithm: null

            # Optional: Encryption key path, i.e. ../key.pem
            # encryption_key_path: null

            # Optional: Encryption key, i.e. contents of key or certificate
            # encryption_key: null
            # whether to check OAuth2 "state": defaults to true
            use_state: true